### ISSUE TITLE
Grocer's Apostrophe

### ISSUE THREAD

**Issue by SpokeyWheeler** [shubhamzanwar/design-patterns#1]
At the end of the first pattern:

> Chester is 2 years old. It's sound is bark

> -------------

> Mr. Buttons is 3 years old. It's sound is meow

"Its" means "belonging to it", "it's" is an abbreviation for "it is".

**Comment by shubhamzanwar** [comment]
LMAO, I actually laughed out loud xD

Thanks, mate!
